### ISSUE TITLE
How to pass in DOCKER_HOST into the run?

### ISSUE THREAD

**Issue by PhilAndrew** [marcuslonnberg/scala-docker#1]
Hi there, just a short question, how can I pass in things like DOCKER_HOST ?

Like this docker command

docker run --name myfabric -Pit -e DOCKER_HOST=http://192.168.59.103:2375 fabric8/fabric8

https://registry.hub.docker.com/u/fabric8/fabric8/

I got fabric8 running and worked out the port binding, but I cannot work out how to set DOCKER_HOST using this code so far. Thanks, Philip

**Comment by marcuslonnberg** [comment]
You pass environment variables via the `ContainerConfig`.

Like this:
```scala
client.run(ContainerConfig(ImageName("fabric8/fabric8"), env = Seq("DOCKER_HOST=http://192.168.59.103:2375")), HostConfig(publishAllPorts = true), name = Some(ContainerName("myfabric")))
```

I will try to find some time to write some documentation and examples for this project soon.

**Comment by PhilAndrew** [comment]
Thanks! I like this project. Its very interesting to control docker from Scala, I can think of so many things to do with this, like when a Scala program needs a database it just controls docker to set it up, as long as it has docker as the entry point.

**Comment by PhilAndrew** [comment]
Im not sure that env is working, I'll need to do more testing.

**Comment by PhilAndrew** [comment]
Yes it works....
